#
#pragma ident	"@(#)Makefile	1.1	00/12/21 SMI"
#
# Copyright (c) 2000 by Sun Microsystems, Inc.
# All rights reserved.
#
# pkgdefs/SUNWpppd/Makefile
#

include ../Makefile.com

DATAFILES= depend

.KEEP_STATE:

all: $(FILES)
install: all pkg

include ../Makefile.targ
