#
#pragma ident	"@(#)Makefile	1.1	01/08/30 SMI"
#
# Copyright (c) 2001 by Sun Microsystems, Inc.
# All rights reserved.
#

include ../Makefile.com

.KEEP_STATE:

DATAFILES += depend

all: $(FILES)
install: all pkg

include ../Makefile.targ
