#
# Copyright 2005 Sun Microsystems, Inc.  All rights reserved.
# Use is subject to license terms.
#

#ident	"@(#)Makefile.lib	1.5	05/08/22 SMI"

include ../../../../../Makefile.cmd
CLEANFILES=lib$(LIB).a $(OBJS) $(COBJS) core

all: lib$(LIB).a

lib$(LIB).a: $(OBJS) $(COBJS) $(DEPLIBS)
	$(AR) r $@ $?
	$(RANLIB) $@

install:
install-man:
depend: depend_src
depend.temp: $(GENSRCS)
gen: $(GENSRCS)
