#
# uts/sun4u/seattle/Makefile.files
# Copyright 2005 Sun Microsystems, Inc.  All rights reserved.
# Use is subject to license terms.
#
#ident	"@(#)Makefile.files	1.1	05/11/04 SMI"
#
#	This Makefile defines all file modules for the directory
#	uts/sun4u/seattle and it's children. These are the source files
#	which are sun4u "implementation architecture" dependent.
#

#
#	object lists
#
# Seattle specific driver module
#

#
# Miscellaneous
#
INC_PATH	+= -I$(UTSBASE)/sun4u/seattle
