#
# Copyright 2003 Sun Microsystems, Inc.  All rights reserved.
# Use is subject to license terms.
#
#pragma ident	"@(#)Makefile	1.1	03/08/05 SMI"
#
 
include ../Makefile.com

.KEEP_STATE:

all: $(FILES) depend postinstall preremove
install: all pkg

include ../Makefile.targ
