#!/bin/sh
#
#pragma ident	"@(#)preremove	1.1	03/08/05 SMI"
#
# Copyright 2003 Sun Microsystems, Inc.  All rights reserved.
# Use is subject to license terms.
#

# Remove driver
/usr/sbin/rem_drv -b ${BASEDIR} tavor

exit 0

