#
# Copyright 2004 Sun Microsystems, Inc.  All rights reserved.
# Use is subject to license terms.
#
# ident	"@(#)Makefile	1.1	04/07/26 SMI"
#

include ../Makefile.com

DATAFILES += i.preserve

.KEEP_STATE:

all: $(FILES) depend postinstall postremove
install: all pkg

include ../Makefile.targ
