#!/sbin/sh
#
# Copyright 2004 Sun Microsystems, Inc.  All rights reserved.
# Use is subject to license terms.
#
# ident	"@(#)postremove	1.1	04/07/26 SMI"
#

BD=${BASEDIR:-/}
if grep -w rtls $BD/etc/name_to_major > /dev/null 2>&1
then
	rem_drv -b ${BD} rtls
	if [ $? -ne 0 ]
	then
		exit 1 	
	fi
fi
exit 0
