#!/sbin/sh
#
# Copyright 2003 Sun Microsystems, Inc.  All rights reserved.
# Use is subject to license terms.

# ident	"@(#)postremove	1.1	03/02/22 SMI"
#
BD=${BASEDIR:-/}
if grep "\<adpu320\>" $BD/etc/name_to_major > /dev/null 2>&1
then
	rem_drv -b ${BD} adpu320
fi
exit 0
