#!/sbin/sh
#
# Copyright 2004 Sun Microsystems, Inc.  All rights reserved.
# Use is subject to license terms.
#
# ident	"@(#)postremove	1.1	04/04/13 SMI"
#

BD=${BASEDIR:-/}
if grep "\<amr\>" $BD/etc/name_to_major > /dev/null 2>&1
then
	rem_drv -b ${BD} amr
fi
exit 0
