#
# Copyright 2004 Sun Microsystems, Inc.  All rights reserved.
# Use is subject to license terms.
#

# ident	"@(#)Makefile	1.1	04/05/10 SMI"

include ../Makefile.com

.KEEP_STATE:

DATAFILES = depend

all: $(FILES)
install: all pkg

include ../Makefile.targ
