#
# Copyright 2003 Sun Microsystems, Inc.  All rights reserved.
# Use is subject to license terms.
#
#ident	"@(#)Makefile	1.1	03/12/15 SMI"
#
# pkgdefs/SUNWipfu
#

include ../Makefile.com

.KEEP_STATE:

DATAFILES = depend

all: $(FILES)
install: all pkg

include ../Makefile.targ
