#
# Copyright 2004 Sun Microsystems, Inc.  All rights reserved.
# Use is subject to license terms.
#
# ident	"@(#)Makefile	1.3	04/04/29 SMI"
#
# lib/libresolv2/irs/sparcv9/Makefile
#

include ../Makefile.com
include ../../../Makefile.lib.64

install: all $(ROOTLIBDIR64) .WAIT $(ROOTLIBS64)
