# Copyright 2003 Sun Microsystems, Inc.  All rights reserved.
# Use is subject to license terms.
#
#pragma ident	"@(#)Makefile	1.1	03/10/23 SMI"
#

include ../Makefile.com

all: $(FILES) depend
install: all pkg    

include ../Makefile.targ


