#
# Copyright 2004 Sun Microsystems, Inc.  All rights reserved.
# Use is subject to license terms.
#
# ident	"@(#)Makefile	1.3	04/04/29 SMI"
#
# lib/libresolv2/irs/i386/Makefile
#

include ../Makefile.com

install: all $(ROOTLIBDIR) .WAIT $(ROOTLIBS)
