#
#pragma ident	"@(#)Makefile	1.3	00/07/17 SMI"
#
# Copyright 1995 by Sun Microsystems, Inc.
# All rights reserved.
#

include ../Makefile.com

DATAFILES +=

.KEEP_STATE:

all: $(FILES)
install: all pkg

include ../Makefile.targ
