#
# Copyright 2003 Sun Microsystems, Inc.  All rights reserved.
# Use is subject to license terms.
#
# ident	"@(#)Makefile	1.1	03/07/16 SMI"
#
# lib/libsasl/plugins/cram/Makefile
#

include		../Makefile.subdirs
