#
# Copyright (c) 2001 by Sun Microsystems, Inc.
# All rights reserved.
#
# ident	"@(#)Makefile	1.1	01/12/28 SMI"
#

include ../Makefile.com

install: all $(ROOTLIBS) .WAIT $(ROOTLINKS) $(ROOTLINT) $(ROOTSFWSRCFILES)
