#
#pragma ident	"@(#)Makefile.sub	1.5	00/07/17 SMI"
#
PROG=nsgmls
OBJS=nsgmls.o SgmlsEventHandler.o RastEventHandler.o StringSet.o nsgmls_inst.o
INCLUDE=
XLIBS=../lib/libsp.a
GENSRCS=nsgmls_inst.cxx NsgmlsMessages.h RastEventHandlerMessages.h
