#
# Copyright 2005 Sun Microsystems, Inc.  All rights reserved.
# Use is subject to license terms.
#
#ident	"@(#)Makefile	1.6	05/01/21 SMI"
#

include ../Makefile.com

DATAFILES = depend i.preserve i.manifest

.KEEP_STATE:

all: $(FILES) preremove
install: all pkg

include ../Makefile.targ
