#
# Copyright 2005 Sun Microsystems, Inc.  All rights reserved.
# Use is subject to license terms.
#
# ident	"@(#)Makefile.grub	1.1	05/04/15 SMI"
#

PLATFORM	= i86pc

ROOT_BOOT_GRUB	= $(ROOT)/boot/grub
ROOT_PLAT_GRUB	= $(ROOT)/platform/$(PLATFORM)/boot/grub
ROOT_SRC	= $(ROOT)/usr/share/src/grub
